tasks:
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
  - before: yarn install

vscode:
  extensions:
    - tabnine.tabnine-vscode@3.2.17:16841d6c91c484eaeb3e800aedbc99fe